# Tarea 1

## Analísis exploratorio del Dataset 
Dataset: SSNMX_catalogo_19000101_20250213 obtenido de http://www.ssn.unam.mx/

In [1]:
# Librerías necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import os

### Cargar el Dataset

In [2]:
archivo = "SSNMX_catalogo_19000101_20250213.csv"
data = pd.read_csv(archivo)
data

C:\Users\Dell Latitude\AppData\Local\Temp\ipykernel_8204\720289594.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(archivo)

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,20/01/1900,00:33:30,7.4,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",20/01/1900,06:33:30,revisado
1,16/05/1900,14:12:00,6.9,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",16/05/1900,20:12:00,revisado
2,05/03/1901,04:45:00,6.9,25.000,-110.000,33.0,"100 km al NORESTE de LA PAZ, BCS",05/03/1901,10:45:00,revisado
3,08/12/1901,20:17:00,7,26.000,-110.000,33.0,"83 km al OESTE de AHOME, SIN",09/12/1901,02:17:00,revisado
4,16/01/1902,17:19:00,7,17.620,-99.720,33.0,"21 km al OESTE de ZUMPANGO DEL RIO, GRO",16/01/1902,23:19:00,revisado
...,...,...,...,...,...,...,...,...,...,...
332386,13/02/2025,04:45:07,3.3,16.410,-98.442,35.0,"30 km al SUR de OMETEPEC, GRO",13/02/2025,10:45:07,verificado
332387,13/02/2025,04:54:04,3.5,17.657,-95.412,38.3,"37 km al SUR de J RODRIGUEZ CLARA, VER",13/02/2025,10:54:04,verificado
332388,13/02/2025,08:25:52,4.0,14.816,-98.058,16.0,"148 km al SUROESTE de RIO GRANDE, OAX",13/02/2025,14:25:52,verificado
332389,13/02/2025,08:42:33,4.0,15.782,-96.221,37.2,"9 km al OESTE de CRUCECITA, OAX",13/02/2025,14:42:33,verificado
332390,13/02/2025,13:52:56,4.1,15.638,-93.243,97.6,"6 km al SUROESTE de PIJIJIAPAN, CHIS",13/02/2025,19:52:56,verificado

In [3]:
data.describe()

             Latitud      Longitud    Profundidad
count  332391.000000  332391.00000  332391.000000
mean       18.033864     -99.37387      32.030894
std         4.229140       5.99640      36.170389
min        10.271000    -120.59500       0.000000
25%        15.931300    -101.76400      10.000000
50%        16.567300     -98.08920      16.100000
75%        18.154700     -94.91020      37.300000
max        38.092300     -85.54670     338.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332391 entries, 0 to 332390
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Fecha                       332391 non-null  object
 1   Hora                        332391 non-null  object
 2   Magnitud                    332391 non-null  object
 3   Latitud                     332391 non-null  float64
 4   Longitud                    332391 non-null  float64
 5   Profundidad                 332391 non-null  float64
 6   Referencia de localizacion  332391 non-null  object
 7   Fecha UTC                   332391 non-null  object
 8   Hora UTC                    332391 non-null  object
 9   Estatus                     332391 non-null  object
dtypes: float64(3), object(7)
memory usage: 25.4+ MB

Como podemos comprobar, las unicas columnas que se cargan como tipos de datos flotantes son las de Latitud, Longitud y Profundidad.
Por lo que podemos concluir que algunas otras como Magnitud que debería ser un valor numerico, puede contar con valores atipicos o que no pertenenezcan al mismo tipo de dato.

In [5]:
for column in data.columns:
    print(column)
    print("Valores nulos", data[column].isna().sum())
    print()

Fecha
Valores nulos 0

Hora
Valores nulos 0

Magnitud
Valores nulos 0

Latitud
Valores nulos 0

Longitud
Valores nulos 0

Profundidad
Valores nulos 0

Referencia de localizacion
Valores nulos 0

Fecha UTC
Valores nulos 0

Hora UTC
Valores nulos 0

Estatus
Valores nulos 0

In [6]:
data_clean = data.copy()

In [7]:
# Definir los valores que representan nulos
null_values = ["NA", "None", "-", "", "null", "no calculable"]

# Reemplazar esos valores con NaN
data_clean.replace(null_values, np.nan, inplace=True)

data_clean

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,20/01/1900,00:33:30,7.4,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",20/01/1900,06:33:30,revisado
1,16/05/1900,14:12:00,6.9,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",16/05/1900,20:12:00,revisado
2,05/03/1901,04:45:00,6.9,25.000,-110.000,33.0,"100 km al NORESTE de LA PAZ, BCS",05/03/1901,10:45:00,revisado
3,08/12/1901,20:17:00,7,26.000,-110.000,33.0,"83 km al OESTE de AHOME, SIN",09/12/1901,02:17:00,revisado
4,16/01/1902,17:19:00,7,17.620,-99.720,33.0,"21 km al OESTE de ZUMPANGO DEL RIO, GRO",16/01/1902,23:19:00,revisado
...,...,...,...,...,...,...,...,...,...,...
332386,13/02/2025,04:45:07,3.3,16.410,-98.442,35.0,"30 km al SUR de OMETEPEC, GRO",13/02/2025,10:45:07,verificado
332387,13/02/2025,04:54:04,3.5,17.657,-95.412,38.3,"37 km al SUR de J RODRIGUEZ CLARA, VER",13/02/2025,10:54:04,verificado
332388,13/02/2025,08:25:52,4.0,14.816,-98.058,16.0,"148 km al SUROESTE de RIO GRANDE, OAX",13/02/2025,14:25:52,verificado
332389,13/02/2025,08:42:33,4.0,15.782,-96.221,37.2,"9 km al OESTE de CRUCECITA, OAX",13/02/2025,14:42:33,verificado
332390,13/02/2025,13:52:56,4.1,15.638,-93.243,97.6,"6 km al SUROESTE de PIJIJIAPAN, CHIS",13/02/2025,19:52:56,verificado

In [8]:
for column in data_clean.columns:
    print(column)
    print("Valores nulos", data_clean[column].isna().sum())
    print()

Fecha
Valores nulos 0

Hora
Valores nulos 0

Magnitud
Valores nulos 17649

Latitud
Valores nulos 0

Longitud
Valores nulos 0

Profundidad
Valores nulos 0

Referencia de localizacion
Valores nulos 0

Fecha UTC
Valores nulos 0

Hora UTC
Valores nulos 0

Estatus
Valores nulos 0

In [9]:
# Eliminar filas con valores nulos
data_clean.dropna(inplace=True)

# Reiniciar los índices después de eliminar filas
data_clean.reset_index(drop=True, inplace=True)

data_clean

,Fecha,Hora,Magnitud,Latitud,Longitud,Profundidad,Referencia de localizacion,Fecha UTC,Hora UTC,Estatus
0,20/01/1900,00:33:30,7.4,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",20/01/1900,06:33:30,revisado
1,16/05/1900,14:12:00,6.9,20.000,-105.000,33.0,"71 km al NOROESTE de AUTLAN DE NAVARRO, JAL",16/05/1900,20:12:00,revisado
2,05/03/1901,04:45:00,6.9,25.000,-110.000,33.0,"100 km al NORESTE de LA PAZ, BCS",05/03/1901,10:45:00,revisado
3,08/12/1901,20:17:00,7,26.000,-110.000,33.0,"83 km al OESTE de AHOME, SIN",09/12/1901,02:17:00,revisado
4,16/01/1902,17:19:00,7,17.620,-99.720,33.0,"21 km al OESTE de ZUMPANGO DEL RIO, GRO",16/01/1902,23:19:00,revisado
...,...,...,...,...,...,...,...,...,...,...
314737,13/02/2025,04:45:07,3.3,16.410,-98.442,35.0,"30 km al SUR de OMETEPEC, GRO",13/02/2025,10:45:07,verificado
314738,13/02/2025,04:54:04,3.5,17.657,-95.412,38.3,"37 km al SUR de J RODRIGUEZ CLARA, VER",13/02/2025,10:54:04,verificado
314739,13/02/2025,08:25:52,4.0,14.816,-98.058,16.0,"148 km al SUROESTE de RIO GRANDE, OAX",13/02/2025,14:25:52,verificado
314740,13/02/2025,08:42:33,4.0,15.782,-96.221,37.2,"9 km al OESTE de CRUCECITA, OAX",13/02/2025,14:42:33,verificado
314741,13/02/2025,13:52:56,4.1,15.638,-93.243,97.6,"6 km al SUROESTE de PIJIJIAPAN, CHIS",13/02/2025,19:52:56,verificado

In [11]:
data_clean.to_csv("SSNMX_clean.csv", index=False)